name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  BASEURL: ${{ vars.BASEURL }}

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Testing
    defaults:
      run:
        working-directory: ./framework

    steps:
      - uses: actions/checkout@v4
      - name: Set node version
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      # Install and start the CatCafe API
      - name: Install and start API
        working-directory: ./CatCafeProject
        run: |
          npm install
          npm run dev &  
          sleep 10        
      # Back to the test framework
      - name: Run npm install and lint
        run: |
            npm install
            npm run lint
      - name: Test
        run: npm run test