name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  BASEURL: ${{ vars.BASEURL }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Test Step
        uses: actions/setup-node@v1
        with:
          node-version: "18.x"
      - run: |
            npm install
            npm run dev &
            npx wait-on http://localhost:3000
        working-directory: ./CatCafeProject
      - run: |
            npm install
            npm run lint
            npm run test
        working-directory: ./framework
